/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.routines;


import com.sivalabs.bookmarks.jooq.JooqDb;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FnCalculateDiscount extends AbstractRoutine<BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>jooq_db.fn_calculate_discount.RETURN_VALUE</code>.
     */
    public static final Parameter<BigDecimal> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.DECIMAL(10, 2), false, false);

    /**
     * The parameter <code>jooq_db.fn_calculate_discount.p_customer_type</code>.
     */
    public static final Parameter<String> P_CUSTOMER_TYPE = Internal.createParameter("p_customer_type", SQLDataType.VARCHAR(50), false, false);

    /**
     * The parameter <code>jooq_db.fn_calculate_discount.p_category</code>.
     */
    public static final Parameter<String> P_CATEGORY = Internal.createParameter("p_category", SQLDataType.VARCHAR(50), false, false);

    /**
     * The parameter <code>jooq_db.fn_calculate_discount.p_quantity</code>.
     */
    public static final Parameter<Integer> P_QUANTITY = Internal.createParameter("p_quantity", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>jooq_db.fn_calculate_discount.p_price</code>.
     */
    public static final Parameter<BigDecimal> P_PRICE = Internal.createParameter("p_price", SQLDataType.DECIMAL(10, 2), false, false);

    /**
     * Create a new routine call instance
     */
    public FnCalculateDiscount() {
        super("fn_calculate_discount", JooqDb.JOOQ_DB, SQLDataType.DECIMAL(10, 2));

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_CUSTOMER_TYPE);
        addInParameter(P_CATEGORY);
        addInParameter(P_QUANTITY);
        addInParameter(P_PRICE);
    }

    /**
     * Set the <code>p_customer_type</code> parameter IN value to the routine
     */
    public void setPCustomerType(String value) {
        setValue(P_CUSTOMER_TYPE, value);
    }

    /**
     * Set the <code>p_customer_type</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    public void setPCustomerType(Field<String> field) {
        setField(P_CUSTOMER_TYPE, field);
    }

    /**
     * Set the <code>p_category</code> parameter IN value to the routine
     */
    public void setPCategory(String value) {
        setValue(P_CATEGORY, value);
    }

    /**
     * Set the <code>p_category</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public void setPCategory(Field<String> field) {
        setField(P_CATEGORY, field);
    }

    /**
     * Set the <code>p_quantity</code> parameter IN value to the routine
     */
    public void setPQuantity(Integer value) {
        setValue(P_QUANTITY, value);
    }

    /**
     * Set the <code>p_quantity</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public void setPQuantity(Field<Integer> field) {
        setField(P_QUANTITY, field);
    }

    /**
     * Set the <code>p_price</code> parameter IN value to the routine
     */
    public void setPPrice(BigDecimal value) {
        setValue(P_PRICE, value);
    }

    /**
     * Set the <code>p_price</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setPPrice(Field<BigDecimal> field) {
        setField(P_PRICE, field);
    }
}
