/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.routines;


import com.sivalabs.bookmarks.jooq.JooqDb;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Getorderdiscount extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>jooq_db.GetOrderDiscount.p_order_id</code>.
     */
    public static final Parameter<Integer> P_ORDER_ID = Internal.createParameter("p_order_id", SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Getorderdiscount() {
        super("GetOrderDiscount", JooqDb.JOOQ_DB);

        addInParameter(P_ORDER_ID);
    }

    /**
     * Set the <code>p_order_id</code> parameter IN value to the routine
     */
    public void setPOrderId(Integer value) {
        setValue(P_ORDER_ID, value);
    }
}
