/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq;


import com.sivalabs.bookmarks.jooq.tables.OrderItems;
import com.sivalabs.bookmarks.jooq.tables.Orders;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in jooq_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ORDERS_CUSTOMER_ID = Internal.createIndex(DSL.name("customer_id"), Orders.ORDERS, new OrderField[] { Orders.ORDERS.CUSTOMER_ID }, false);
    public static final Index ORDER_ITEMS_ORDER_ID = Internal.createIndex(DSL.name("order_id"), OrderItems.ORDER_ITEMS, new OrderField[] { OrderItems.ORDER_ITEMS.ORDER_ID }, false);
    public static final Index ORDER_ITEMS_PRODUCT_ID = Internal.createIndex(DSL.name("product_id"), OrderItems.ORDER_ITEMS, new OrderField[] { OrderItems.ORDER_ITEMS.PRODUCT_ID }, false);
}
