/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq;


import com.sivalabs.bookmarks.jooq.tables.BookmarkTag;
import com.sivalabs.bookmarks.jooq.tables.Bookmarks;
import com.sivalabs.bookmarks.jooq.tables.Customers;
import com.sivalabs.bookmarks.jooq.tables.DiscountRules;
import com.sivalabs.bookmarks.jooq.tables.OrderItems;
import com.sivalabs.bookmarks.jooq.tables.Orders;
import com.sivalabs.bookmarks.jooq.tables.Products;
import com.sivalabs.bookmarks.jooq.tables.Tags;
import com.sivalabs.bookmarks.jooq.tables.UserPreferences;
import com.sivalabs.bookmarks.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JooqDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq_db</code>
     */
    public static final JooqDb JOOQ_DB = new JooqDb();

    /**
     * The table <code>jooq_db.bookmark_tag</code>.
     */
    public final BookmarkTag BOOKMARK_TAG = BookmarkTag.BOOKMARK_TAG;

    /**
     * The table <code>jooq_db.bookmarks</code>.
     */
    public final Bookmarks BOOKMARKS = Bookmarks.BOOKMARKS;

    /**
     * The table <code>jooq_db.customers</code>.
     */
    public final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>jooq_db.discount_rules</code>.
     */
    public final DiscountRules DISCOUNT_RULES = DiscountRules.DISCOUNT_RULES;

    /**
     * The table <code>jooq_db.order_items</code>.
     */
    public final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>jooq_db.orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>jooq_db.products</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>jooq_db.tags</code>.
     */
    public final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>jooq_db.user_preferences</code>.
     */
    public final UserPreferences USER_PREFERENCES = UserPreferences.USER_PREFERENCES;

    /**
     * The table <code>jooq_db.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private JooqDb() {
        super("jooq_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            BookmarkTag.BOOKMARK_TAG,
            Bookmarks.BOOKMARKS,
            Customers.CUSTOMERS,
            DiscountRules.DISCOUNT_RULES,
            OrderItems.ORDER_ITEMS,
            Orders.ORDERS,
            Products.PRODUCTS,
            Tags.TAGS,
            UserPreferences.USER_PREFERENCES,
            Users.USERS
        );
    }
}
