/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq;


import com.sivalabs.bookmarks.jooq.tables.Bookmarks;
import com.sivalabs.bookmarks.jooq.tables.Customers;
import com.sivalabs.bookmarks.jooq.tables.DiscountRules;
import com.sivalabs.bookmarks.jooq.tables.OrderItems;
import com.sivalabs.bookmarks.jooq.tables.Orders;
import com.sivalabs.bookmarks.jooq.tables.Products;
import com.sivalabs.bookmarks.jooq.tables.Tags;
import com.sivalabs.bookmarks.jooq.tables.UserPreferences;
import com.sivalabs.bookmarks.jooq.tables.Users;
import com.sivalabs.bookmarks.jooq.tables.records.BookmarksRecord;
import com.sivalabs.bookmarks.jooq.tables.records.CustomersRecord;
import com.sivalabs.bookmarks.jooq.tables.records.DiscountRulesRecord;
import com.sivalabs.bookmarks.jooq.tables.records.OrderItemsRecord;
import com.sivalabs.bookmarks.jooq.tables.records.OrdersRecord;
import com.sivalabs.bookmarks.jooq.tables.records.ProductsRecord;
import com.sivalabs.bookmarks.jooq.tables.records.TagsRecord;
import com.sivalabs.bookmarks.jooq.tables.records.UserPreferencesRecord;
import com.sivalabs.bookmarks.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * jooq_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BookmarksRecord> KEY_BOOKMARKS_PRIMARY = Internal.createUniqueKey(Bookmarks.BOOKMARKS, DSL.name("KEY_bookmarks_PRIMARY"), new TableField[] { Bookmarks.BOOKMARKS.ID }, true);
    public static final UniqueKey<CustomersRecord> KEY_CUSTOMERS_PRIMARY = Internal.createUniqueKey(Customers.CUSTOMERS, DSL.name("KEY_customers_PRIMARY"), new TableField[] { Customers.CUSTOMERS.CUSTOMER_ID }, true);
    public static final UniqueKey<DiscountRulesRecord> KEY_DISCOUNT_RULES_PRIMARY = Internal.createUniqueKey(DiscountRules.DISCOUNT_RULES, DSL.name("KEY_discount_rules_PRIMARY"), new TableField[] { DiscountRules.DISCOUNT_RULES.RULE_ID }, true);
    public static final UniqueKey<OrderItemsRecord> KEY_ORDER_ITEMS_PRIMARY = Internal.createUniqueKey(OrderItems.ORDER_ITEMS, DSL.name("KEY_order_items_PRIMARY"), new TableField[] { OrderItems.ORDER_ITEMS.ORDER_ITEM_ID }, true);
    public static final UniqueKey<OrdersRecord> KEY_ORDERS_PRIMARY = Internal.createUniqueKey(Orders.ORDERS, DSL.name("KEY_orders_PRIMARY"), new TableField[] { Orders.ORDERS.ORDER_ID }, true);
    public static final UniqueKey<ProductsRecord> KEY_PRODUCTS_PRIMARY = Internal.createUniqueKey(Products.PRODUCTS, DSL.name("KEY_products_PRIMARY"), new TableField[] { Products.PRODUCTS.PRODUCT_ID }, true);
    public static final UniqueKey<TagsRecord> KEY_TAGS_PRIMARY = Internal.createUniqueKey(Tags.TAGS, DSL.name("KEY_tags_PRIMARY"), new TableField[] { Tags.TAGS.ID }, true);
    public static final UniqueKey<TagsRecord> KEY_TAGS_TAG_NAME_UNIQUE = Internal.createUniqueKey(Tags.TAGS, DSL.name("KEY_tags_tag_name_unique"), new TableField[] { Tags.TAGS.NAME }, true);
    public static final UniqueKey<UserPreferencesRecord> KEY_USER_PREFERENCES_PRIMARY = Internal.createUniqueKey(UserPreferences.USER_PREFERENCES, DSL.name("KEY_user_preferences_PRIMARY"), new TableField[] { UserPreferences.USER_PREFERENCES.ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_PRIMARY"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_USER_EMAIL_UNIQUE = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_user_email_unique"), new TableField[] { Users.USERS.EMAIL }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<OrderItemsRecord, OrdersRecord> ORDER_ITEMS_IBFK_1 = Internal.createForeignKey(OrderItems.ORDER_ITEMS, DSL.name("order_items_ibfk_1"), new TableField[] { OrderItems.ORDER_ITEMS.ORDER_ID }, Keys.KEY_ORDERS_PRIMARY, new TableField[] { Orders.ORDERS.ORDER_ID }, true);
    public static final ForeignKey<OrderItemsRecord, ProductsRecord> ORDER_ITEMS_IBFK_2 = Internal.createForeignKey(OrderItems.ORDER_ITEMS, DSL.name("order_items_ibfk_2"), new TableField[] { OrderItems.ORDER_ITEMS.PRODUCT_ID }, Keys.KEY_PRODUCTS_PRIMARY, new TableField[] { Products.PRODUCTS.PRODUCT_ID }, true);
    public static final ForeignKey<OrdersRecord, CustomersRecord> ORDERS_IBFK_1 = Internal.createForeignKey(Orders.ORDERS, DSL.name("orders_ibfk_1"), new TableField[] { Orders.ORDERS.CUSTOMER_ID }, Keys.KEY_CUSTOMERS_PRIMARY, new TableField[] { Customers.CUSTOMERS.CUSTOMER_ID }, true);
}
