/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq;


import com.sivalabs.bookmarks.jooq.routines.FnCalculateDiscount;
import com.sivalabs.bookmarks.jooq.routines.Getorderdiscount;

import java.math.BigDecimal;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in jooq_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>jooq_db.fn_calculate_discount</code>
     */
    public static BigDecimal fnCalculateDiscount(
          Configuration configuration
        , String pCustomerType
        , String pCategory
        , Integer pQuantity
        , BigDecimal pPrice
    ) {
        FnCalculateDiscount f = new FnCalculateDiscount();
        f.setPCustomerType(pCustomerType);
        f.setPCategory(pCategory);
        f.setPQuantity(pQuantity);
        f.setPPrice(pPrice);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>jooq_db.fn_calculate_discount</code> as a field.
     */
    public static Field<BigDecimal> fnCalculateDiscount(
          String pCustomerType
        , String pCategory
        , Integer pQuantity
        , BigDecimal pPrice
    ) {
        FnCalculateDiscount f = new FnCalculateDiscount();
        f.setPCustomerType(pCustomerType);
        f.setPCategory(pCategory);
        f.setPQuantity(pQuantity);
        f.setPPrice(pPrice);

        return f.asField();
    }

    /**
     * Get <code>jooq_db.fn_calculate_discount</code> as a field.
     */
    public static Field<BigDecimal> fnCalculateDiscount(
          Field<String> pCustomerType
        , Field<String> pCategory
        , Field<Integer> pQuantity
        , Field<BigDecimal> pPrice
    ) {
        FnCalculateDiscount f = new FnCalculateDiscount();
        f.setPCustomerType(pCustomerType);
        f.setPCategory(pCategory);
        f.setPQuantity(pQuantity);
        f.setPPrice(pPrice);

        return f.asField();
    }

    /**
     * Call <code>jooq_db.GetOrderDiscount</code>
     */
    public static void getorderdiscount(
          Configuration configuration
        , Integer pOrderId
    ) {
        Getorderdiscount p = new Getorderdiscount();
        p.setPOrderId(pOrderId);

        p.execute(configuration);
    }
}
