/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq;


import com.sivalabs.bookmarks.jooq.tables.BookmarkTag;
import com.sivalabs.bookmarks.jooq.tables.Bookmarks;
import com.sivalabs.bookmarks.jooq.tables.Customers;
import com.sivalabs.bookmarks.jooq.tables.DiscountRules;
import com.sivalabs.bookmarks.jooq.tables.OrderItems;
import com.sivalabs.bookmarks.jooq.tables.Orders;
import com.sivalabs.bookmarks.jooq.tables.Products;
import com.sivalabs.bookmarks.jooq.tables.Tags;
import com.sivalabs.bookmarks.jooq.tables.UserPreferences;
import com.sivalabs.bookmarks.jooq.tables.Users;


/**
 * Convenience access to all tables in jooq_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>jooq_db.bookmark_tag</code>.
     */
    public static final BookmarkTag BOOKMARK_TAG = BookmarkTag.BOOKMARK_TAG;

    /**
     * The table <code>jooq_db.bookmarks</code>.
     */
    public static final Bookmarks BOOKMARKS = Bookmarks.BOOKMARKS;

    /**
     * The table <code>jooq_db.customers</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>jooq_db.discount_rules</code>.
     */
    public static final DiscountRules DISCOUNT_RULES = DiscountRules.DISCOUNT_RULES;

    /**
     * The table <code>jooq_db.order_items</code>.
     */
    public static final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>jooq_db.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>jooq_db.products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>jooq_db.tags</code>.
     */
    public static final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>jooq_db.user_preferences</code>.
     */
    public static final UserPreferences USER_PREFERENCES = UserPreferences.USER_PREFERENCES;

    /**
     * The table <code>jooq_db.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
