/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables;


import com.sivalabs.bookmarks.jooq.JooqDb;
import com.sivalabs.bookmarks.jooq.tables.records.BookmarkTagRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookmarkTag extends TableImpl<BookmarkTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq_db.bookmark_tag</code>
     */
    public static final BookmarkTag BOOKMARK_TAG = new BookmarkTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookmarkTagRecord> getRecordType() {
        return BookmarkTagRecord.class;
    }

    /**
     * The column <code>jooq_db.bookmark_tag.bookmark_id</code>.
     */
    public final TableField<BookmarkTagRecord, Long> BOOKMARK_ID = createField(DSL.name("bookmark_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>jooq_db.bookmark_tag.tag_id</code>.
     */
    public final TableField<BookmarkTagRecord, Long> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private BookmarkTag(Name alias, Table<BookmarkTagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BookmarkTag(Name alias, Table<BookmarkTagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>jooq_db.bookmark_tag</code> table reference
     */
    public BookmarkTag(String alias) {
        this(DSL.name(alias), BOOKMARK_TAG);
    }

    /**
     * Create an aliased <code>jooq_db.bookmark_tag</code> table reference
     */
    public BookmarkTag(Name alias) {
        this(alias, BOOKMARK_TAG);
    }

    /**
     * Create a <code>jooq_db.bookmark_tag</code> table reference
     */
    public BookmarkTag() {
        this(DSL.name("bookmark_tag"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqDb.JOOQ_DB;
    }

    @Override
    public BookmarkTag as(String alias) {
        return new BookmarkTag(DSL.name(alias), this);
    }

    @Override
    public BookmarkTag as(Name alias) {
        return new BookmarkTag(alias, this);
    }

    @Override
    public BookmarkTag as(Table<?> alias) {
        return new BookmarkTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookmarkTag rename(String name) {
        return new BookmarkTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookmarkTag rename(Name name) {
        return new BookmarkTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookmarkTag rename(Table<?> name) {
        return new BookmarkTag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookmarkTag where(Condition condition) {
        return new BookmarkTag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookmarkTag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookmarkTag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookmarkTag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BookmarkTag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BookmarkTag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BookmarkTag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BookmarkTag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookmarkTag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookmarkTag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
