/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables;


import com.sivalabs.bookmarks.jooq.JooqDb;
import com.sivalabs.bookmarks.jooq.Keys;
import com.sivalabs.bookmarks.jooq.tables.records.BookmarksRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Bookmarks extends TableImpl<BookmarksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq_db.bookmarks</code>
     */
    public static final Bookmarks BOOKMARKS = new Bookmarks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookmarksRecord> getRecordType() {
        return BookmarksRecord.class;
    }

    /**
     * The column <code>jooq_db.bookmarks.id</code>.
     */
    public final TableField<BookmarksRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>jooq_db.bookmarks.url</code>.
     */
    public final TableField<BookmarksRecord, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>jooq_db.bookmarks.title</code>.
     */
    public final TableField<BookmarksRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>jooq_db.bookmarks.created_at</code>.
     */
    public final TableField<BookmarksRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>jooq_db.bookmarks.updated_at</code>.
     */
    public final TableField<BookmarksRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>jooq_db.bookmarks.created_by</code>.
     */
    public final TableField<BookmarksRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    private Bookmarks(Name alias, Table<BookmarksRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Bookmarks(Name alias, Table<BookmarksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>jooq_db.bookmarks</code> table reference
     */
    public Bookmarks(String alias) {
        this(DSL.name(alias), BOOKMARKS);
    }

    /**
     * Create an aliased <code>jooq_db.bookmarks</code> table reference
     */
    public Bookmarks(Name alias) {
        this(alias, BOOKMARKS);
    }

    /**
     * Create a <code>jooq_db.bookmarks</code> table reference
     */
    public Bookmarks() {
        this(DSL.name("bookmarks"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqDb.JOOQ_DB;
    }

    @Override
    public Identity<BookmarksRecord, Long> getIdentity() {
        return (Identity<BookmarksRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<BookmarksRecord> getPrimaryKey() {
        return Keys.KEY_BOOKMARKS_PRIMARY;
    }

    @Override
    public Bookmarks as(String alias) {
        return new Bookmarks(DSL.name(alias), this);
    }

    @Override
    public Bookmarks as(Name alias) {
        return new Bookmarks(alias, this);
    }

    @Override
    public Bookmarks as(Table<?> alias) {
        return new Bookmarks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Bookmarks rename(String name) {
        return new Bookmarks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bookmarks rename(Name name) {
        return new Bookmarks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bookmarks rename(Table<?> name) {
        return new Bookmarks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bookmarks where(Condition condition) {
        return new Bookmarks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bookmarks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bookmarks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bookmarks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bookmarks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bookmarks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bookmarks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bookmarks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bookmarks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bookmarks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
