/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables;


import com.sivalabs.bookmarks.jooq.JooqDb;
import com.sivalabs.bookmarks.jooq.Keys;
import com.sivalabs.bookmarks.jooq.tables.records.DiscountRulesRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DiscountRules extends TableImpl<DiscountRulesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq_db.discount_rules</code>
     */
    public static final DiscountRules DISCOUNT_RULES = new DiscountRules();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DiscountRulesRecord> getRecordType() {
        return DiscountRulesRecord.class;
    }

    /**
     * The column <code>jooq_db.discount_rules.rule_id</code>.
     */
    public final TableField<DiscountRulesRecord, Integer> RULE_ID = createField(DSL.name("rule_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>jooq_db.discount_rules.customer_type</code>.
     */
    public final TableField<DiscountRulesRecord, String> CUSTOMER_TYPE = createField(DSL.name("customer_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>jooq_db.discount_rules.product_category</code>.
     */
    public final TableField<DiscountRulesRecord, String> PRODUCT_CATEGORY = createField(DSL.name("product_category"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>jooq_db.discount_rules.min_qty</code>.
     */
    public final TableField<DiscountRulesRecord, Integer> MIN_QTY = createField(DSL.name("min_qty"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>jooq_db.discount_rules.max_qty</code>.
     */
    public final TableField<DiscountRulesRecord, Integer> MAX_QTY = createField(DSL.name("max_qty"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>jooq_db.discount_rules.discount_percent</code>.
     */
    public final TableField<DiscountRulesRecord, BigDecimal> DISCOUNT_PERCENT = createField(DSL.name("discount_percent"), SQLDataType.DECIMAL(5, 2).nullable(false), this, "");

    private DiscountRules(Name alias, Table<DiscountRulesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DiscountRules(Name alias, Table<DiscountRulesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>jooq_db.discount_rules</code> table reference
     */
    public DiscountRules(String alias) {
        this(DSL.name(alias), DISCOUNT_RULES);
    }

    /**
     * Create an aliased <code>jooq_db.discount_rules</code> table reference
     */
    public DiscountRules(Name alias) {
        this(alias, DISCOUNT_RULES);
    }

    /**
     * Create a <code>jooq_db.discount_rules</code> table reference
     */
    public DiscountRules() {
        this(DSL.name("discount_rules"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqDb.JOOQ_DB;
    }

    @Override
    public Identity<DiscountRulesRecord, Integer> getIdentity() {
        return (Identity<DiscountRulesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DiscountRulesRecord> getPrimaryKey() {
        return Keys.KEY_DISCOUNT_RULES_PRIMARY;
    }

    @Override
    public List<Check<DiscountRulesRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_qty_range"), "(`max_qty` >= `min_qty`)", true)
        );
    }

    @Override
    public DiscountRules as(String alias) {
        return new DiscountRules(DSL.name(alias), this);
    }

    @Override
    public DiscountRules as(Name alias) {
        return new DiscountRules(alias, this);
    }

    @Override
    public DiscountRules as(Table<?> alias) {
        return new DiscountRules(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DiscountRules rename(String name) {
        return new DiscountRules(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DiscountRules rename(Name name) {
        return new DiscountRules(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DiscountRules rename(Table<?> name) {
        return new DiscountRules(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DiscountRules where(Condition condition) {
        return new DiscountRules(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DiscountRules where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DiscountRules where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DiscountRules where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DiscountRules where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DiscountRules where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DiscountRules where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DiscountRules where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DiscountRules whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DiscountRules whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
