/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.records;


import com.sivalabs.bookmarks.jooq.tables.Bookmarks;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookmarksRecord extends UpdatableRecordImpl<BookmarksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jooq_db.bookmarks.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq_db.bookmarks.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jooq_db.bookmarks.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq_db.bookmarks.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jooq_db.bookmarks.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq_db.bookmarks.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jooq_db.bookmarks.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>jooq_db.bookmarks.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>jooq_db.bookmarks.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>jooq_db.bookmarks.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>jooq_db.bookmarks.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>jooq_db.bookmarks.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookmarksRecord
     */
    public BookmarksRecord() {
        super(Bookmarks.BOOKMARKS);
    }

    /**
     * Create a detached, initialised BookmarksRecord
     */
    public BookmarksRecord(Long id, String url, String title, LocalDateTime createdAt, LocalDateTime updatedAt, Long createdBy) {
        super(Bookmarks.BOOKMARKS);

        setId(id);
        setUrl(url);
        setTitle(title);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
