/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.records;


import com.sivalabs.bookmarks.jooq.tables.BookmarkTag;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookmarkTagRecord extends TableRecordImpl<BookmarkTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jooq_db.bookmark_tag.bookmark_id</code>.
     */
    public void setBookmarkId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq_db.bookmark_tag.bookmark_id</code>.
     */
    public Long getBookmarkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jooq_db.bookmark_tag.tag_id</code>.
     */
    public void setTagId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq_db.bookmark_tag.tag_id</code>.
     */
    public Long getTagId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookmarkTagRecord
     */
    public BookmarkTagRecord() {
        super(BookmarkTag.BOOKMARK_TAG);
    }

    /**
     * Create a detached, initialised BookmarkTagRecord
     */
    public BookmarkTagRecord(Long bookmarkId, Long tagId) {
        super(BookmarkTag.BOOKMARK_TAG);

        setBookmarkId(bookmarkId);
        setTagId(tagId);
        resetChangedOnNotNull();
    }
}
