/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.records;


import com.sivalabs.bookmarks.jooq.tables.Customers;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomersRecord extends UpdatableRecordImpl<CustomersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jooq_db.customers.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq_db.customers.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooq_db.customers.customer_name</code>.
     */
    public void setCustomerName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq_db.customers.customer_name</code>.
     */
    public String getCustomerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jooq_db.customers.customer_type</code>.
     */
    public void setCustomerType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq_db.customers.customer_type</code>.
     */
    public String getCustomerType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(Integer customerId, String customerName, String customerType) {
        super(Customers.CUSTOMERS);

        setCustomerId(customerId);
        setCustomerName(customerName);
        setCustomerType(customerType);
        resetChangedOnNotNull();
    }
}
