/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.records;


import com.sivalabs.bookmarks.jooq.tables.DiscountRules;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DiscountRulesRecord extends UpdatableRecordImpl<DiscountRulesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jooq_db.discount_rules.rule_id</code>.
     */
    public void setRuleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq_db.discount_rules.rule_id</code>.
     */
    public Integer getRuleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooq_db.discount_rules.customer_type</code>.
     */
    public void setCustomerType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq_db.discount_rules.customer_type</code>.
     */
    public String getCustomerType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jooq_db.discount_rules.product_category</code>.
     */
    public void setProductCategory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq_db.discount_rules.product_category</code>.
     */
    public String getProductCategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jooq_db.discount_rules.min_qty</code>.
     */
    public void setMinQty(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>jooq_db.discount_rules.min_qty</code>.
     */
    public Integer getMinQty() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>jooq_db.discount_rules.max_qty</code>.
     */
    public void setMaxQty(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>jooq_db.discount_rules.max_qty</code>.
     */
    public Integer getMaxQty() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>jooq_db.discount_rules.discount_percent</code>.
     */
    public void setDiscountPercent(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>jooq_db.discount_rules.discount_percent</code>.
     */
    public BigDecimal getDiscountPercent() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiscountRulesRecord
     */
    public DiscountRulesRecord() {
        super(DiscountRules.DISCOUNT_RULES);
    }

    /**
     * Create a detached, initialised DiscountRulesRecord
     */
    public DiscountRulesRecord(Integer ruleId, String customerType, String productCategory, Integer minQty, Integer maxQty, BigDecimal discountPercent) {
        super(DiscountRules.DISCOUNT_RULES);

        setRuleId(ruleId);
        setCustomerType(customerType);
        setProductCategory(productCategory);
        setMinQty(minQty);
        setMaxQty(maxQty);
        setDiscountPercent(discountPercent);
        resetChangedOnNotNull();
    }
}
