/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.records;


import com.sivalabs.bookmarks.jooq.tables.Orders;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jooq_db.orders.order_id</code>.
     */
    public void setOrderId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq_db.orders.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooq_db.orders.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq_db.orders.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jooq_db.orders.order_date</code>.
     */
    public void setOrderDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq_db.orders.order_date</code>.
     */
    public LocalDateTime getOrderDate() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Integer orderId, Integer customerId, LocalDateTime orderDate) {
        super(Orders.ORDERS);

        setOrderId(orderId);
        setCustomerId(customerId);
        setOrderDate(orderDate);
        resetChangedOnNotNull();
    }
}
