/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.records;


import com.sivalabs.bookmarks.jooq.tables.UserPreferences;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserPreferencesRecord extends UpdatableRecordImpl<UserPreferencesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jooq_db.user_preferences.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq_db.user_preferences.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jooq_db.user_preferences.theme</code>.
     */
    public void setTheme(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq_db.user_preferences.theme</code>.
     */
    public String getTheme() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jooq_db.user_preferences.language</code>.
     */
    public void setLanguage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq_db.user_preferences.language</code>.
     */
    public String getLanguage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jooq_db.user_preferences.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>jooq_db.user_preferences.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>jooq_db.user_preferences.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>jooq_db.user_preferences.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserPreferencesRecord
     */
    public UserPreferencesRecord() {
        super(UserPreferences.USER_PREFERENCES);
    }

    /**
     * Create a detached, initialised UserPreferencesRecord
     */
    public UserPreferencesRecord(Long id, String theme, String language, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(UserPreferences.USER_PREFERENCES);

        setId(id);
        setTheme(theme);
        setLanguage(language);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
